name: Run Colab Notebook Every 24 Hours

on:
  schedule:
    - cron: ('30 3 * * *')  # This will run every day at midnight UTC ----- Remove the "()" brackets to run the code
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run_colab_script:
    runs-on: ubuntu-latest  # Use an Ubuntu environment

    steps:
      # Checkout your repository to access the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python (install the required Python version)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the version of Python you need

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread twilio oauth2client  # Install required Python packages

      # Run the Python script
      - name: Run Python Script
        run: |
          python run_colab.py  # Replace with your script filename
